### ISSUE TITLE
Chainsaw man manga part 2

### ISSUE THREAD

**Issue by rBB62** [croberts22/myanilist-bugs#72] opened 2022-08-24 21:33 UTC
The app works really well except Chainsaw man part 2 manga doesn’t update correctly. This is the only animanga that I have experienced this issue with.

**Comment by rBB62** [comment] 2022-08-24 21:34
![EF4E43EE-F7BE-409B-B6E3-3EA8931DC05A](https://user-images.githubusercontent.com/112028323/186527770-9e0064c3-c0f4-4575-a25f-1773ec06c2c0.jpeg)

**Comment by Cmp21** [comment] 2022-09-03 23:02
I believe this is because AniList ended up removing that entry from the site and continuing the original one. However, it seems the app is still seeing the series as complete, at least on the Manga tab

![FCCA9344-A6E2-4A74-83C2-3658AFE647CF](https://user-images.githubusercontent.com/13479481/188290081-b9699022-dbc9-4930-8430-10fc2c39ccda.jpeg)

**Comment by dominiktacadena** [comment] 2022-09-20 14:14
yes please fix this!

**Comment by tactidact** [comment] 2022-10-29 05:18
this particular issue is really annoying, I'm at chapter 108/97 and I have to view on AniList and make chapter updates on the website instead of just in the app

**Comment by damianhxy** [comment] 2022-11-09 03:21
Same here, I have to manually update on AniList.

**Comment by frootsnacc** [comment] 2022-11-12 23:29
I can’t believe this hasn’t been fixed yet even though Chainsaw Man’s been back for 4 months already.

The page for Nichijou has the same issue.

**Comment by croberts22** [comment] 2022-11-15 04:40
Hey all, I cannot control when AniList.co decides to either continue, delete, or merge series into others, as I do not own the database for that. "Chainsaw Man: Dai-2 Bu" does not actually exist in the AniList database anymore as far as I'm aware (i.e. I can't find it even on their website).

I can however fix the issue where the total chapter/volume count is persistent even from these updates (it's generally rare that these values get removed, which is why it's not responding to those updates). I'm working on a quick hotfix release to display some messaging about recent "slowness" from AniList's side, but you can expect that part of the bugfix to be in version 3.0.6.

**Comment by croberts22** [comment] 2022-11-23 23:29
This fix is now available in the latest beta of 3.0.6 (build 4) 🚀

As a reminder: "Chainsaw Man: Dai-2 Bu" does not actually exist in the AniList database anymore, so you will need to update the existing Chainsaw Man entry instead. Going into the details page for this should update automatically, but if it doesn't, you can pull to refresh and it should update there.

**Comment by croberts22** [comment] 2022-11-24 00:16
And now available as v3.0.6 in the App Store 🚀 I will leave this issue open if any issues occur, but will close this in a few days if no issues are discovered.

**Comment by Cmp21** [comment] 2022-11-25 03:14
Confirmed this fixed it for me. I didn’t have to go into the details page, it fixed on a refresh of the main Manga tab. Thank you!

**Closed** 2022-11-27 17:50 UTC
Labels: bug: saving, anilist issue
