### ISSUE TITLE
I can't rate animes

### ISSUE THREAD

**Issue by Aledpl5** [croberts22/myanilist-bugs#74] opened 2022-10-23 19:54 UTC
With the last update of AniList, I cannot rate with the new layout the animes that I complete.

**Comment by croberts22** [comment] 2022-10-24 03:35
Hello @Aledpl5, could you be more specific? i.e. can you provide clear and reproducible steps that lead to the root cause you are describing? A video would be helpful here.

**Comment by Aledpl5** [comment] 2022-10-24 11:12
I attach you a video [here](https://drive.google.com/file/d/1pM110luWZOZoJPUd1c5K4xJC7pCN5JMv/view?usp=sharing).
I try to explain the problem: when I swipe an anime to mark it as completed or I visit an anime page and I want to rate it, this layout appears and asks me to write the grade. When I click the done botton, my vote di cancelled and so I cannot rate.

**Comment by croberts22** [comment] 2022-10-26 01:53
Thanks for the link, I requested access to view it.

**Comment by Aledpl5** [comment] 2022-10-26 05:05
I sent you the access to the video

**Comment by croberts22** [comment] 2022-10-27 14:54
Thank you! I see the issue, and this will be fixed in the next version (3.0.1). This will also be available in the next beta if you are on that list. Thanks for reporting this!

**Comment by Aledpl5** [comment] 2022-10-28 07:26
Thank you so much

**Closed** 2022-11-15 04:42 UTC
Labels: bug, pending deployment, regression
