### ISSUE TITLE
Lock Screen Notifications don’t Sync with app

### ISSUE THREAD

**Issue by Cazcy** [croberts22/myanilist-bugs#28] opened 2021-12-28 23:31 UTC
The Notifications on the Lock Screen allow you to mark an episode as watched and sync with the app. However after the last update the notifications no longer sync with the app. So the episode status in the app will end up being wrong until you manual open the app and update the shows. When you complete a show as well from notifications you no longer get a notification to rate the show. You have to complete the show in the app since the notifications don’t work. Please fix this is the feature I use the most and it’s now broken.

**Comment by YDraig** [comment] 2022-01-04 05:56
Related/duplicate of #27

**Comment by croberts22** [comment] 2022-01-09 22:20
As mentioned, this is a duplicate and will be closed. Thank you for filing this!

**Closed by croberts22** 2022-01-09 22:20 UTC
Labels: needs triage, bug: tokubetsu
